name: Update packages
on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:
    inputs:
      force_update:
        description: "Force update all packages"
        required: false
        type: boolean
        default: false

env:
  REPO_RELEASE_NAME: "current"
  REPO_FILENAME: "hypergonial"
  REPO_URL: "https://github.com/hypergonial/arch_repo/releases/download/current"

jobs:
  check:
    name: Check for package updates
    runs-on: ubuntu-slim
    outputs:
      needs_run: ${{ steps.gen_matrix.outputs.is_empty == 'false' }}
      matrix: ${{ steps.gen_matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Check all packages for updates
        id: gen_matrix
        shell: bash
        env:
          FORCE_UPDATE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force_update == 'true' }}
        run: |
          # Outputs: is_empty, matrix
          python3 .github/workflows/check_packages.py

  build:
    name: Build ${{ matrix.name }} ${{ matrix.latest_version }}-${{ matrix.desired_pkgrel }}
    needs: check
    if: needs.check.outputs.needs_run == 'true'
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    strategy:
      matrix: ${{ fromJson(needs.check.outputs.matrix) }}
    steps:
      - name: Update system
        run: |
          pacman-key --init
          pacman -Syu --noconfirm

      - name: Install tools
        run: |
          pacman -Sy --noconfirm --needed git tar zstd gnupg curl

      - name: Get job count
        id: jobs
        env:
          PARALLEL_BUILD: ${{ matrix.parallel_build }}
        run: |
          if [ "$PARALLEL_BUILD" = "true" ]; then
            count=$(nproc)
          else
            count=1
          fi
          echo "count=$count" >> $GITHUB_OUTPUT
          echo "Using $count parallel jobs for building."

      - name: Create builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: repo

      - name: Update PKGBUILD
        uses: ./repo/.github/actions/update-pkgbuild
        with:
          version: ${{ matrix.latest_version }}
          pkgrel: ${{ matrix.desired_pkgrel }}
          file: "repo/${{ matrix.name }}/PKGBUILD"

      # TODO: Signing the package would be nice

      - name: Make package
        id: package
        working-directory: repo/${{ matrix.name }}
        env:
          MAKEFLAGS: "-j${{ steps.jobs.outputs.count }}"
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ steps.jobs.outputs.count }}
        run: |
          chown -R builder:builder .
          sudo --preserve-env -u builder makepkg --syncdeps --noconfirm --needed --cleanbuild
          echo path="$(ls -1 *.pkg.tar.zst | grep -v -- '-debug-' | head -n1)" >> $GITHUB_OUTPUT
          chown -R root:root .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pkg-${{ matrix.name }}
          path: repo/${{ matrix.name }}/${{ steps.package.outputs.path }}
          retention-days: 1

  update_repo:
    name: Update repository files
    needs: [check, build]
    if: needs.check.outputs.needs_run == 'true'
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    permissions:
      contents: write
    steps:
      - name: Update system
        run: |
          pacman-key --init
          pacman -Syu --noconfirm

      - name: Install tools
        run: |
          pacman -Sy --noconfirm --needed git tar zstd gnupg curl github-cli

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: pkg-*
          path: packages

      - name: Download existing repository db
        shell: bash
        continue-on-error: true
        run: |
          curl -sfL -o ${{ env.REPO_FILENAME }}.db.tar.zst "${{ env.REPO_URL }}/${{ env.REPO_FILENAME }}.db.tar.zst"
          curl -sfL -o ${{ env.REPO_FILENAME }}.files.tar.zst "${{ env.REPO_URL }}/${{ env.REPO_FILENAME }}.files.tar.zst"
          ln -s ${{ env.REPO_FILENAME }}.db.tar.zst ${{ env.REPO_FILENAME }}.db
          ln -s ${{ env.REPO_FILENAME }}.files.tar.zst ${{ env.REPO_FILENAME }}.files

      - name: Update repository db
        id: repo
        run: |
          # Find every package file and add it to the repo
          for pkg in $(find packages -name '*.pkg.tar.zst'); do
            repo-add "${{ env.REPO_FILENAME }}.db.tar.zst" "$pkg"
          done

          echo path=${{ env.REPO_FILENAME }}.db >> $GITHUB_OUTPUT
          echo files_path=${{ env.REPO_FILENAME }}.files >> $GITHUB_OUTPUT
          echo path_zst=${{ env.REPO_FILENAME }}.db.tar.zst >> $GITHUB_OUTPUT
          echo files_path_zst=${{ env.REPO_FILENAME }}.files.tar.zst >> $GITHUB_OUTPUT

      - name: Create Release (if not exists)
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! gh release view "${{ env.REPO_RELEASE_NAME }}" --repo "${{ github.repository }}" > /dev/null 2>&1; then
            gh release create "${{ env.REPO_RELEASE_NAME }}" --repo "${{ github.repository }}" --title "${{ env.REPO_RELEASE_NAME }}" --notes "Arch Package Repository"
          fi

      - name: Update repository files
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${{ env.REPO_RELEASE_NAME }}" "repo/${{ steps.repo.outputs.path }}" --repo "${{ github.repository }}" --clobber
          gh release upload "${{ env.REPO_RELEASE_NAME }}" "repo/${{ steps.repo.outputs.files_path }}" --repo "${{ github.repository }}" --clobber
          gh release upload "${{ env.REPO_RELEASE_NAME }}" "repo/${{ steps.repo.outputs.path_zst }}" --repo "${{ github.repository }}" --clobber
          gh release upload "${{ env.REPO_RELEASE_NAME }}" "repo/${{ steps.repo.outputs.files_path_zst }}" --repo "${{ github.repository }}" --clobber

          for pkg in $(find packages -name '*.pkg.tar.zst'); do
            gh release upload "${{ env.REPO_RELEASE_NAME }}" "$pkg" --repo "${{ github.repository }}" --clobber
          done
